#!/usr/bin/env bash

set -euo pipefail

# scontrol-like DVC SLURM job monitoring and control tool:
# show, put on hold, release, cancel (groups of) stage/commit/push/cleanup jobs


### same as in slurm_enqueue.sh
DVC_SLURM_CONTROL_DEBUGGING=0  # set to 1 for debugging

debug() {
    if [ "${DVC_SLURM_CONTROL_DEBUGGING}" -eq 1 ]; then
        "$@"
    fi
}

SCRIPT_NAME="$(basename "$0")"
log () {
    echo "${SCRIPT_NAME}: $1"
}

log_error () {
    log "$1"
    exit 1
}

dvc_stage_from_dep () {
    echo "${1##*:}"
}

dvc_yaml_from_dep () {
    echo "${1%:*}"
}

dvc_root="$(dvc root)"

# Append dvc root to SLURM job ID (due to repo-level lock)
dvc_stage_slurm_prefix="dvc"
dvc_stage_slurm_suffix=$(python3 -c "import hashlib; print(hashlib.sha1(\"$(realpath "${dvc_root}")\".encode(\"utf-8\")).hexdigest()[:12])") # "$(realpath "${dvc_root}" | sha1sum | head -c 12)"
get_dvc_slurm_job_name () { # compute SLURM job name for DVC stage/commit in $1
  echo "${dvc_stage_slurm_prefix}_$(dvc_stage_from_dep "$1")_${dvc_stage_slurm_suffix}"
}

dvc_slurm_put_jobs_on_hold () {
    dvc_job_name="$(get_dvc_slurm_job_name ".*")"
    while IFS=',' read -r job_id job_name job_status job_command job_reason; do
        if [[ -n "${job_id}" && -n "${job_command}" && -n "${job_reason}" ]]; then
            read -r job_id <<<"${job_id}"
            read -r job_name <<<"${job_name}"
            read -r job_status <<<"${job_status}"
            read -ra job_command <<<"${job_command}"
            read -r job_reason <<<"${job_reason}"
            if [[ "${job_name}" =~ ${dvc_job_name} && $(basename ${job_command[0]}) == sbatch_dvc_$1* && "${job_reason}" != JobHeldUser ]]; then
                if [[ ${job_status} == PENDING ]]; then
                    log "Putting pending job ${job_name}[$(basename "${job_command[0]}")] (reason ${job_reason} != JobHeldUser) at ${job_id} on hold (release using 'dvc_scontrol release $1')."
                    scontrol hold ${job_id} # or: scontrol update JobID=${job_id} StartTime=now+300  # for 5 min delay
                elif [[ ${job_status} == RUNNING ]]; then
                    log "Requeuing on hold running job ${job_name}[$(basename "${job_command[0]}")] (reason ${job_reason} != JobHeldUser) at ${job_id} on hold (release using 'dvc_scontrol release $1')."
                    scontrol requeuehold ${job_id}
                else
                    log "Ignoring job ${job_name}[$(basename "${job_command[0]}")] at ${job_id} with status ${job_status}."
                fi
            fi
        fi
    done <<<$(squeue -u $(id -un) --format="%.30A,%.200j,%30T,%.200o,%.30r" --sort=-S -h)
    log "All jobs of $(id -un) held. To make sure that no other users run DVC commands on this repo use 'dvc_scontrol show $1'."
}

dvc_slurm_release_jobs () {
    dvc_job_name="$(get_dvc_slurm_job_name ".*")"
    while IFS=',' read -r job_id job_name job_command job_reason; do
        if [[ -n "${job_id}" && "${job_command}" && -n "${job_reason}" ]]; then
            read -r job_id <<<"${job_id}"
            read -r job_name <<<"${job_name}"
            read -ra job_command <<<"${job_command}"
            read -r job_reason <<<"${job_reason}"
            if [[ "${job_name}" =~ ${dvc_job_name} && $(basename ${job_command[0]}) == sbatch_dvc_$1* ]]; then
                log "Releasing job ${job_name}[$(basename "${job_command[0]}")] (reason ${job_reason}) at ${job_id}."
                scontrol release ${job_id}
            fi
        fi
    done <<<$(squeue -u $(id -un) --format="%.30A,%.200j,%.200o,%.30r" --sort=-S -h)
}


dvc_slurm_show_jobs () {
    dvc_job_name="$(get_dvc_slurm_job_name ".*")"
    dvc_job_ids=()
    while IFS=',' read -r job_id job_name job_command; do
        if [[ -n "${job_id}" && "${job_command}" ]]; then
            read -r job_id <<<"${job_id}"
            read -r job_name <<<"${job_name}"
            read -ra job_command <<<"${job_command}"
            if [[ "${job_name}" =~ ${dvc_job_name} && $(basename ${job_command[0]}) == sbatch_dvc_$1* ]]; then
                dvc_job_ids+=(${job_id})
            fi
        fi
    done <<<$(squeue -u $(id -un) --format="%.30A,%.200j,%.200o" --sort=-S -h)
    dvc_job_ids="$(printf ",%s" "${dvc_job_ids[@]}")"
    log "DVC $1 jobs:"
    debug set -x
    squeue --job "${dvc_job_ids:1}" --format="%.15u %.15A %.10r %.10M %.10L %.60j %.130Z" --sort=-S 
    debug set +x
}


dvc_slurm_cancel_jobs () {
    dvc_job_name="$(get_dvc_slurm_job_name ".*")"
    while IFS=',' read -r job_id job_name job_command; do
        if [[ -n "${job_id}" && "${job_command}" ]]; then
            read -r job_id <<<"${job_id}"
            read -r job_name <<<"${job_name}"
            read -ra job_command <<<"${job_command}"
            if [[ "${job_name}" =~ ${dvc_job_name} &&  $(basename ${job_command[0]}) == sbatch_dvc_$1* ]]; then
                log "Cancelling job ${job_name}[$(basename "${job_command[0]}")] at ${job_id}."
                scancel ${job_id}
            fi
        fi
    done <<<$(squeue -u $(id -un) --format="%.30A,%.200j,%.200o" --sort=-S -h)
}

# Define the help message
print_usage() {
    cat << EOF
Usage: $0 COMMAND DVC_JOB_TYPES

COMMAND is the action to take on a DVC job group, one of: show, hold, release, cancel

DVC_JOB_TYPES is the group of DVC jobs to control, a comma-separated list that can include: stage, commit, push or cleanup (or simply all)
EOF
}


if [ $# -eq 0 ] || [[ " $@ " =~ " --help " ]]; then
    print_usage
    exit 0
fi

if [[ $# -ne 2 ]]; then
    log_error "Error: Wrong number of parameters (expected 2): '$@'"
fi

# Parse list of DVC job types
dvc_job_type="$2"
if [ "${dvc_job_type}" == "all" ]; then
    dvc_job_type="stage,commit,push,cleanup"
fi

IFS=',' read -ra dvc_job_type_list <<<"${dvc_job_type}"


case $1 in
    hold)
        debug set -x
        for job_type in "${dvc_job_type_list[@]}"; do
            dvc_slurm_put_jobs_on_hold "${job_type}"
        done
        ;;
    release)
        debug set -x
        for job_type in "${dvc_job_type_list[@]}"; do
            dvc_slurm_release_jobs "${job_type}"
        done
        ;;
    show)
        debug set -x
        for job_type in "${dvc_job_type_list[@]}"; do
            dvc_slurm_show_jobs "${job_type}"
        done
        ;;
    cancel)
        debug set -x
        for job_type in "${dvc_job_type_list[@]}"; do
            dvc_slurm_cancel_jobs "${job_type}"
        done
        ;;
    *)
        echo "Unknown option '$1' (choose either hold, release [combined with a dvc operation such as commit, push, cleanup], or show, cancel [additionally with stage])"
        exit 1
        ;;
esac

