# An input stage for configuration files
# Serves both for data fetched from external sources as well as as a workaround
# for the missing --file option of dvc add in newer releases

config_stage:
  # no data dependencies
  output:  # output data
    config:
      stage_data: &output_config [*app_name, config, *config_group_name, output]
      command_line_options:
        --config-output: *output_config

  dvc: [*output_config, ".."]
